main: com.herobane.home.Main
name: Home
version: 1.0
author: Herobane
commands:
  sethome:
    description: defini le home du joueur
  home:
    description: teleporte le joueur a son home
  setwarp:
    description: defini un warp commun a tout les joueurs
  warp:
    description: teleporte le joueur a un warp
